title: BlueStar Theme Demo Site
description: A demo site showcasing the BlueStar Jekyll theme.
baseurl: "/BlueStar-Theme" # repository name for GitHub Pages
url: "https://zbule.github.io"


# Optional: add plugins if needed
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections (if you want to demo blog posts or custom content)
collections:
  posts:
    output: true
