title: BlueStar Theme Demo Site
description: A demo site showcasing the BlueStar Jekyll theme.
baseurl: "" # leave this empty if deploying to main domain
url: "https://yourusername.github.io/bluestar-theme"

remote_theme: zbule/bluestar-theme

# Optional: add plugins if needed
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections (if you want to demo blog posts or custom content)
collections:
  posts:
    output: true
